### ISSUE TITLE
Improve alias style guide

### ISSUE THREAD

**Issue by gabrielpra1** [jungsoft/elixir-style-guide#4]
Our rules aren't clear on how we should deal with aliases with different nested levels. For example:

```elixir
alias MyApp.Z
alias MyApp.{
  A,
  B,
}
```

or 

```elixir
  alias MyApp.{
    A,
    B,
  }
alias MyApp.Z
```

**Comment by eduardoscottini** [comment]
I think the first alias should be the first level and then consider the alphabetical order. 

```elixir
alias MyApp.{
  Repo,
  Zeus,
}
alias MyApp.Accounts.User
alias MyApp.Auth.Tokens
```

**Comment by gabrielpra1** [comment]
What about different modules at the first level?

```elixir
alias Aaa.Aaa
alias MyApp.{
  Repo,
  Zeus,
}
alias MyApp.Accounts.User
```

or 

```elixir
alias MyApp.{
  Repo,
  Zeus,
}
alias Aaa.Aaa
alias MyApp.Accounts.User
```

**Comment by jotaviobiondo** [comment]
Hmm, I think the first is better, because it follows the lexicographical order. If we use the second, for every nested level we will have to order separately. The first is more straightforward, I think.

**Comment by gabrielpra1** [comment]
> Hmm, I think the first is better, because it follows the lexicographical order. If we use the second, for every nested level we will have to order separately. The first is more straightforward, I think.

Agreed! So to summarize, the rule should be to first consider alphabetical order and then consider nesting level, right?

**Comment by jotaviobiondo** [comment]
That's right!
